### ISSUE TITLE
Indie-Sky will not take photo with GPS enabled and no GPS lock

### ISSUE THREAD

**Issue by degan6** [aaronwmorris/indi-allsky#1439]
Again thank you for your work on this software.

Reproduction steps should be, setup with the latest version and enable GPS but ensure you don't have a lock.

I get in my log:

```
2024-08-05T23:14:12.649834-07:00 allsky [INFO] Capture-2-1399/MainThread indi.getTelescopeRaDec() [874]: Telescope Coord: RA 19.08, Dec 45.70
2024-08-05T23:14:12.750474-07:00 allsky [WARNING] Capture-2-1399/MainThread indi.getGpsPosition() [810]: GPS fix not found
2024-08-05T23:14:16.724662-07:00 allsky [ERROR] MainProcess-1231/MainThread allsky._startCaptureWorker() [333]: Capture worker exception: Traceback (most recent call last):
2024-08-05T23:14:16.725397-07:00 allsky [ERROR] MainProcess-1231/MainThread allsky._startCaptureWorker() [333]: Capture worker exception:   File "/home/de/indi-allsky/indi_allsky/capture.py", line 175, in run
2024-08-05T23:14:16.725850-07:00 allsky [ERROR] MainProcess-1231/MainThread allsky._startCaptureWorker() [333]: Capture worker exception:     self.saferun()
2024-08-05T23:14:16.726179-07:00 allsky [ERROR] MainProcess-1231/MainThread allsky._startCaptureWorker() [333]: Capture worker exception:   File "/home/de/indi-allsky/indi_allsky/capture.py", line 348, in saferun
2024-08-05T23:14:16.726545-07:00 allsky [ERROR] MainProcess-1231/MainThread allsky._startCaptureWorker() [333]: Capture worker exception:     self.getGpsPosition()
2024-08-05T23:14:16.726837-07:00 allsky [ERROR] MainProcess-1231/MainThread allsky._startCaptureWorker() [333]: Capture worker exception:   File "/home/de/indi-allsky/indi_allsky/capture.py", line 1148, in getGpsPosition
2024-08-05T23:14:16.727122-07:00 allsky [ERROR] MainProcess-1231/MainThread allsky._startCaptureWorker() [333]: Capture worker exception:     gps_lat, gps_long, gps_elev = self.indiclient.getGpsPosition()
2024-08-05T23:14:16.727388-07:00 allsky [ERROR] MainProcess-1231/MainThread allsky._startCaptureWorker() [333]: Capture worker exception:     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-05T23:14:16.727665-07:00 allsky [ERROR] MainProcess-1231/MainThread allsky._startCaptureWorker() [333]: Capture worker exception: ValueError: not enough values to unpack (expected 3, got 2)
2024-08-05T23:14:16.728015-07:00 allsky [ERROR] MainProcess-1231/MainThread allsky._startCaptureWorker() [333]: Capture worker exception:^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-05T23:14:16.727665-07:00 allsky [ERROR] MainProcess-1231/MainThread allsky._startCaptureWorker() [333]: Capture worker exception: ValueError: not enough values to unpack (expected 3, got 2)
2024-08-05T23:14:16.728015-07:00 allsky [ERROR] MainProcess-1231/MainThread allsky._startCaptureWorker() [333]: Capture worker exception:
```

Looks like it talking about this line:

https://github.com/aaronwmorris/indi-allsky/blame/main/indi_allsky/capture.py#L1148

This is a guess on the cause, but I know when I disable the GPS in the config, I don't get the error and it save pictures.

Thank you again for your work on this project. I hope to do more tests tonight.

**Comment by degan6** [comment]
Thank you!! I'll try this out tonight!

David

**Comment by degan6** [comment]
@aaronwmorris - This seems to be fixed for me! Thank you for the quick fix.

**Comment by degan6** [comment]
/
