### ISSUE TITLE
`Video worker exception` when trying to generate start trails timelapse

### ISSUE THREAD

**Issue by dcinzona** [aaronwmorris/indi-allsky#1683]
Preface: this worked before I added a detection mask png under Processing.

When I try to generate `Generate Keogram/Star Trails`, I get Video worker exception erros and the assets fail to generate (they are saved in the database as generated, but are unavailable for retrieval.
If I `Generate All`, the main timelapse is generated successfully, but the other two or not (same errors).

After adding the detection mask, I unchecked `Star Trails Use Existing Data` (I'm trying again now using the existing data to see if this is the issue).

> unchecked `Star Trails Use Existing Data`

_Spoiler: this appears to have been the issue._

<details><summary>Error Details</summary>
<pre>

24-11-27T14:53:03.579951-05:00 pi5 [ERROR] MainProcess-3114/MainThread allsky._startVideoWorker() [454]: Video worker exception: 
2024-11-27T14:53:03.579921-05:00 pi5 [ERROR] MainProcess-3114/MainThread allsky._startVideoWorker() [454]: Video worker exception: 
2024-11-27T14:53:03.579891-05:00 pi5 [ERROR] MainProcess-3114/MainThread allsky._startVideoWorker() [454]: Video worker exception: cv2.error: OpenCV(4.10.0) /io/opencv/modules/core/src/matrix_iterator.cpp:71: error: (-215:Assertion failed) A.size == arrays[i0]->size in function 'init'
2024-11-27T14:53:03.579861-05:00 pi5 [ERROR] MainProcess-3114/MainThread allsky._startVideoWorker() [454]: Video worker exception:             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-27T14:53:03.579830-05:00 pi5 [ERROR] MainProcess-3114/MainThread allsky._startVideoWorker() [454]: Video worker exception:     m_avg = cv2.mean(image_gray, mask=self._sqm_mask)[0]
2024-11-27T14:53:03.579800-05:00 pi5 [ERROR] MainProcess-3114/MainThread allsky._startVideoWorker() [454]: Video worker exception:   File "/home/gmt/indi-allsky/indi_allsky/starTrails.py", line 296, in processImage
2024-11-27T14:53:03.579770-05:00 pi5 [ERROR] MainProcess-3114/MainThread allsky._startVideoWorker() [454]: Video worker exception:     stg.processImage(image_file_p, image_data, adu=adu, star_count=star_count)
2024-11-27T14:53:03.579740-05:00 pi5 [ERROR] MainProcess-3114/MainThread allsky._startVideoWorker() [454]: Video worker exception:   File "/home/gmt/indi-allsky/indi_allsky/video.py", line 1364, in generateKeogramStarTrails
2024-11-27T14:53:03.579710-05:00 pi5 [ERROR] MainProcess-3114/MainThread allsky._startVideoWorker() [454]: Video worker exception:     action_method(task, **kwargs)
2024-11-27T14:53:03.579680-05:00 pi5 [ERROR] MainProcess-3114/MainThread allsky._startVideoWorker() [454]: Video worker exception:   File "/home/gmt/indi-allsky/indi_allsky/video.py", line 218, in processTask
2024-11-27T14:53:03.579650-05:00 pi5 [ERROR] MainProcess-3114/MainThread allsky._startVideoWorker() [454]: Video worker exception:     self.processTask(v_dict)
2024-11-27T14:53:03.579620-05:00 pi5 [ERROR] MainProcess-3114/MainThread allsky._startVideoWorker() [454]: Video worker exception:   File "/home/gmt/indi-allsky/indi_allsky/video.py", line 185, in saferun
2024-11-27T14:53:03.579588-05:00 pi5 [ERROR] MainProcess-3114/MainThread allsky._startVideoWorker() [454]: Video worker exception:     self.saferun()
2024-11-27T14:53:03.579555-05:00 pi5 [ERROR] MainProcess-3114/MainThread allsky._startVideoWorker() [454]: Video worker exception:   File "/home/gmt/indi-allsky/indi_allsky/video.py", line 157, in run
2024-11-27T14:53:03.579410-05:00 pi5 [ERROR] MainProcess-3114/MainThread allsky._startVideoWorker() [454]: Video worker exception: Traceback (most recent call last):
2024-11-27T14:52:54.392574-05:00 pi5 [INFO] Capture-1-3118/MainThread capture.saferun() [387]: Daytime capture disabled

</pre>
</details> 

[support-info.log](https://github.com/user-attachments/files/17939703/support-info.log)

**Comment by aaronwmorris** [comment]
I think the problem is your detection mask.  Errors like this occur when the size of the mask does not match the images.
