### ISSUE TITLE
indi-allsky stops and doesn't recover when disk is full

### ISSUE THREAD

**Issue by Vertikar** [aaronwmorris/indi-allsky#414]
**Describe the bug**
When the disk is full, image capture stops, and doesn't restart once disk space is freed up

**To Reproduce**
Let disk fill up

**Expected behavior**
Hopefully exceptions could be handled and image capture could restart once there is enough disk space

**Screenshots**
![image](https://user-images.githubusercontent.com/436414/202063781-ad428d36-be72-4740-8320-864e8b299850.png)

**Additional context**
system info:
```
Release 5.4
Uptime 2 days, 9 hours, 42 minutes, 39 seconds
<snip>
System
Python 3.9.2
pyindi 1.9.7
cv2 4.6.0
numpy 1.22.4
ephem 4.1.3
astropy 5.1.1
flask 2.2.2
ccdproc 2.3.1
paramiko 2.12.0
paho.mqtt 1.6.1
dbus 1.3.2
pycurl PycURL/7.45.1 libcurl/7.74.0 GnuTLS/3.7.1 zlib/1.2.11 brotli/1.0.9 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.3.0) libssh2/1.9.0 nghttp2/1.43.0 librtmp/2.3
```
git info:
```
karl@allsky:/opt/indi-allsky $ git show
commit 4ae6eb4003872c99c9b23a893fe363d67499d4b5 (HEAD -> master, origin/master, origin/HEAD)
Merge: 7864aac 5508f4e
Author: Aaron W Morris <aaron@aarmor.net>
Date:   Sat Nov 5 14:23:53 2022 -0400

    Merge pull request #399 from aaronwmorris/dev

    add link to indi config wiki

karl@allsky:/opt/indi-allsky $ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```
Log of error from indi-allsky.log below:

```
Nov 16 08:04:03 allsky [INFO] ImageWorker003 image._convert_16bit_to_8bit() #1592: Resampling image from 16 to 8 bits
Nov 16 08:04:03 allsky [INFO] ImageWorker003 image.calculate_histogram() #1302: Greyscale mean: 80.38
Nov 16 08:04:03 allsky [INFO] ImageWorker003 image.calculate_histogram() #1313: Brightness average: 80.38
Nov 16 08:04:03 allsky [INFO] ImageWorker003 image.calculate_histogram() #1351: Current target ADU: 82.75 (72.75/92.75)
Nov 16 08:04:03 allsky [INFO] ImageWorker003 image.calculate_histogram() #1352: Current ADU history: (6) [81.07, 80.96, 81.26, 80.98, 79.96, 80.38]
Nov 16 08:04:03 allsky [INFO] ImageWorker003 image.calculate_histogram() #1356: ADU average: 80.77
Nov 16 08:04:03 allsky [INFO] ImageWorker003 image.white_balance_manual_bgr() #1518: Applying manual color balance settings
Nov 16 08:04:03 allsky [INFO] ImageWorker003 image.saferun() #415: Image processed in 0.3216 s
Nov 16 08:04:10 allsky [INFO] MainProcess allsky.run() #673: Camera last ready: 7.3s
Nov 16 08:04:10 allsky [INFO] MainProcess allsky.run() #674: Exposure state: OK
Nov 16 08:04:10 allsky [ERROR] MainProcess allsky._startImageWorker() #481: Image worker exception: Traceback (most recent call last):
Nov 16 08:04:10 allsky [ERROR] MainProcess allsky._startImageWorker() #481: Image worker exception:   File "/opt/indi-allsky/indi_allsky/image.py", line 864, in write_status_json
Nov 16 08:04:10 allsky [ERROR] MainProcess allsky._startImageWorker() #481: Image worker exception:     f_indi_status.flush()
Nov 16 08:04:10 allsky [ERROR] MainProcess allsky._startImageWorker() #481: Image worker exception: OSError: [Errno 28] No space left on device
Nov 16 08:04:10 allsky [ERROR] MainProcess allsky._startImageWorker() #481: Image worker exception:
Nov 16 08:04:10 allsky [ERROR] MainProcess allsky._startImageWorker() #481: Image worker exception: During handling of the above exception, another exception occurred:
Nov 16 08:04:10 allsky [ERROR] MainProcess allsky._startImageWorker() #481: Image worker exception:
Nov 16 08:04:10 allsky [ERROR] MainProcess allsky._startImageWorker() #481: Image worker exception: OSError: [Errno 28] No space left on device
Nov 16 08:04:10 allsky [ERROR] MainProcess allsky._startImageWorker() #481: Image worker exception:
Nov 16 08:04:10 allsky [ERROR] MainProcess allsky._startImageWorker() #481: Image worker exception: During handling of the above exception, another exception occurred:
Nov 16 08:04:10 allsky [ERROR] MainProcess allsky._startImageWorker() #481: Image worker exception:
Nov 16 08:04:10 allsky [ERROR] MainProcess allsky._startImageWorker() #481: Image worker exception: Traceback (most recent call last):
Nov 16 08:04:10 allsky [ERROR] MainProcess allsky._startImageWorker() #481: Image worker exception:   File "/opt/indi-allsky/indi_allsky/image.py", line 154, in run
Nov 16 08:04:10 allsky [ERROR] MainProcess allsky._startImageWorker() #481: Image worker exception:     self.saferun()
Nov 16 08:04:10 allsky [ERROR] MainProcess allsky._startImageWorker() #481: Image worker exception:   File "/opt/indi-allsky/indi_allsky/image.py", line 421, in saferun
Nov 16 08:04:10 allsky [ERROR] MainProcess allsky._startImageWorker() #481: Image worker exception:     self.write_status_json(exposure, exp_date, adu, adu_average, blob_stars)  # write json status file
Nov 16 08:04:10 allsky [ERROR] MainProcess allsky._startImageWorker() #481: Image worker exception:   File "/opt/indi-allsky/indi_allsky/image.py", line 865, in write_status_json
Nov 16 08:04:10 allsky [ERROR] MainProcess allsky._startImageWorker() #481: Image worker exception:     f_indi_status.close()
Nov 16 08:04:10 allsky [ERROR] MainProcess allsky._startImageWorker() #481: Image worker exception: OSError: [Errno 28] No space left on device
Nov 16 08:04:10 allsky [ERROR] MainProcess allsky._startImageWorker() #481: Image worker exception:
Nov 16 08:04:10 allsky [INFO] MainProcess allsky._startImageWorker() #488: Starting ImageWorker process
Nov 16 08:04:10 allsky [WARNING] MainProcess image._load_detection_mask() #1736: No detection mask defined
Nov 16 08:04:10 allsky [INFO] MainProcess allsky.detectNight() #1045: Sun altitude: 23:17:17.0
Nov 16 08:04:10 allsky [INFO] MainProcess allsky.detectMoonMode() #1062: Moon altitide: 28:16:25.9, phase 56.6%
Nov 16 08:04:10 allsky [INFO] MainProcess indi.getCcdTemperature() #463: Sensor temperature: 20.2
Nov 16 08:04:10 allsky [INFO] MainProcess allsky._queueManualTasks() #1751: Checking for manually submitted tasks
Nov 16 08:04:17 allsky [INFO] MainProcess allsky.shoot() #1267: Taking 0.00102068 s exposure (gain 0)
Nov 16 08:04:17 allsky [INFO] MainProcess allsky.run() #831: Total time since last exposure 15.0437 s
Nov 16 08:04:17 allsky [INFO] MainProcess indi.newText() #232: new Text DRIVER_INFO for device ZWO CCD ASI224MC
Nov 16 08:04:17 allsky [INFO] MainProcess indi.newMessage() #238: new Message 2022-11-15T21:04:17: [WARNING] Telescope focal length is missing.
Nov 16 08:04:17 allsky [INFO] MainProcess indi.newMessage() #238: new Message 2022-11-15T21:04:17: [WARNING] Telescope aperture is missing.
Nov 16 08:04:17 allsky [INFO] MainProcess indi.newBLOB() #171: new BLOB CCD1
Nov 16 08:04:17 allsky [ERROR] MainProcess allsky.unhandled_exception() #33: An uncaught exception occurred:
Nov 16 08:04:17 allsky [ERROR] MainProcess allsky.unhandled_exception() #34: Type: <class 'OSError'>
Nov 16 08:04:17 allsky [ERROR] MainProcess allsky.unhandled_exception() #35: Value: Not enough space on disk: requested 2545408, available 0. Not enough space on disk: requested 2545408, available 0. [Errno 28] No space left on device
Nov 16 08:04:17 allsky [ERROR] MainProcess allsky.unhandled_exception() #40: '  File "/opt/indi-allsky/indi_allsky/camera/indi.py", line 186, in newBLOB\n    hdulist.writeto(f_tmpfile)\n'
Nov 16 08:04:17 allsky [ERROR] MainProcess allsky.unhandled_exception() #40: '  File "/opt/indi-allsky/virtualenv/indi-allsky/lib/python3.9/site-packages/astropy/io/fits/hdu/hdulist.py", line 951, in writeto\n    hdu._postwriteto()\n'
Nov 16 08:04:17 allsky [ERROR] MainProcess allsky.unhandled_exception() #40: '  File "/usr/lib/python3.9/contextlib.py", line 135, in __exit__\n    self.gen.throw(type, value, traceback)\n'
Nov 16 08:04:17 allsky [ERROR] MainProcess allsky.unhandled_exception() #40: '  File "/opt/indi-allsky/virtualenv/indi-allsky/lib/python3.9/site-packages/astropy/io/fits/util.py", line 848, in _free_space_check\n    raise OSError(error_message + str(exc))\n'
Nov 16 08:04:20 allsky [INFO] MainProcess allsky.run() #673: Camera last ready: 17.7s
Nov 16 08:04:20 allsky [INFO] MainProcess allsky.run() #674: Exposure state: BUSY
Nov 16 08:04:20 allsky [INFO] MainProcess allsky.detectNight() #1045: Sun altitude: 23:19:17.6
Nov 16 08:04:20 allsky [INFO] MainProcess allsky.detectMoonMode() #1062: Moon altitide: 28:15:51.8, phase 56.6%
Nov 16 08:04:20 allsky [INFO] MainProcess indi.getCcdTemperature() #463: Sensor temperature: 20.2
Nov 16 08:04:20 allsky [INFO] MainProcess allsky._queueManualTasks() #1751: Checking for manually submitted tasks
Nov 16 08:04:30 allsky [INFO] MainProcess allsky.run() #673: Camera last ready: 27.8s
Nov 16 08:04:30 allsky [INFO] MainProcess allsky.run() #674: Exposure state: BUSY
```
Log from webapp-indi-allsky.log
```
karl@allsky:/opt/allsky/images $ tail /var/log/indi-allsky/webapp-indi-allsky.log
Nov 16 01:14:32 allsky [INFO] MainProcess views.dispatch_request() #2615: Variance of laplacien in 0.1791 s
Nov 16 01:14:37 allsky [INFO] MainProcess views.dispatch_request() #2615: Variance of laplacien in 0.2359 s
Nov 16 01:14:42 allsky [INFO] MainProcess views.dispatch_request() #2615: Variance of laplacien in 0.2002 s
Nov 16 01:15:40 allsky [INFO] MainProcess glogging.info() #264: Worker reloading: config.json modified
Nov 16 01:15:40 allsky [INFO] MainProcess views.dispatch_request() #1261: Wrote new config.json
Nov 16 01:15:41 allsky [INFO] MainProcess glogging.info() #264: Worker exiting (pid: 626519)
Nov 16 01:15:42 allsky gunicorn.indi_allsky.wsgi.error: [628661] Booting worker with pid: 628661
Nov 16 01:16:07 allsky [INFO] MainProcess views.dispatch_request() #1861: Command return: /org/freedesktop/systemd1/job/73
Nov 16 08:14:36 allsky [INFO] MainProcess forms.__init__() #1739: Dates processed in 0.0213 s
Nov 16 12:40:25 allsky [INFO] MainProcess forms.__init__() #1739: Dates processed in 0.0066 s
```

Output from systemctl:

```
karl@allsky:/opt/allsky/images $ systemctl status --user indi-allsky.service
● indi-allsky.service - Indi AllSky Service
     Loaded: loaded (/home/karl/.config/systemd/user/indi-allsky.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2022-11-15 22:22:07 AEDT; 14h ago
    Process: 628673 ExecReload=/bin/kill -HUP $MAINPID (code=exited, status=0/SUCCESS)
   Main PID: 626344 (python3)
      Tasks: 8 (limit: 779)
        CPU: 1h 5min 55.695s
     CGroup: /user.slice/user-1000.slice/user@1000.service/app.slice/indi-allsky.service
             ├─626344 /opt/indi-allsky/virtualenv/indi-allsky/bin/python3 allsky.py --config /etc/indi-allsky/config.json --log syslog run
             ├─628677 /opt/indi-allsky/virtualenv/indi-allsky/bin/python3 allsky.py --config /etc/indi-allsky/config.json --log syslog run
             ├─628678 /opt/indi-allsky/virtualenv/indi-allsky/bin/python3 allsky.py --config /etc/indi-allsky/config.json --log syslog run
             └─633122 /opt/indi-allsky/virtualenv/indi-allsky/bin/python3 allsky.py --config /etc/indi-allsky/config.json --log syslog run

Nov 16 12:53:02 allsky python3[626344]: [INFO] MainProcess allsky.detectNight() #1045: Sun altitude: 70:39:41.1
Nov 16 12:53:02 allsky python3[626344]: [INFO] MainProcess allsky.detectMoonMode() #1062: Moon altitide: -10:27:32.0, phase 54.7%
Nov 16 12:53:02 allsky python3[626344]: [INFO] MainProcess indi.getCcdTemperature() #463: Sensor temperature: 20.2
Nov 16 12:53:02 allsky python3[626344]: [INFO] MainProcess allsky._queueManualTasks() #1751: Checking for manually submitted tasks
Nov 16 12:53:12 allsky python3[626344]: [INFO] MainProcess allsky.run() #673: Camera last ready: 17349.5s
Nov 16 12:53:12 allsky python3[626344]: [INFO] MainProcess allsky.run() #674: Exposure state: BUSY
Nov 16 12:53:12 allsky python3[626344]: [INFO] MainProcess allsky.detectNight() #1045: Sun altitude: 70:39:55.5
Nov 16 12:53:12 allsky python3[626344]: [INFO] MainProcess allsky.detectMoonMode() #1062: Moon altitide: -10:29:21.1, phase 54.7%
Nov 16 12:53:12 allsky python3[626344]: [INFO] MainProcess indi.getCcdTemperature() #463: Sensor temperature: 20.2
Nov 16 12:53:12 allsky python3[626344]: [INFO] MainProcess allsky._queueManualTasks() #1751: Checking for manually submitted tasks
karl@allsky:/opt/allsky/images $ systemctl status --user indiserver.service
● indiserver.service - Indi Server
     Loaded: loaded (/home/karl/.config/systemd/user/indiserver.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2022-11-15 22:19:56 AEDT; 14h ago
   Main PID: 626205 (indiserver)
      Tasks: 7 (limit: 779)
        CPU: 3min 8.381s
     CGroup: /user.slice/user-1000.slice/user@1000.service/app.slice/indiserver.service
             ├─626205 /usr/bin/indiserver indi_asi_ccd
             └─626206 indi_asi_ccd

Nov 16 08:02:02 allsky indiserver[626205]: 2022-11-15T21:02:02: Driver indi_asi_ccd: Received 1 fds
Nov 16 08:02:17 allsky indiserver[626205]: 2022-11-15T21:02:17: Driver indi_asi_ccd: Received 1 fds
Nov 16 08:02:32 allsky indiserver[626205]: 2022-11-15T21:02:32: Driver indi_asi_ccd: Received 1 fds
Nov 16 08:02:47 allsky indiserver[626205]: 2022-11-15T21:02:47: Driver indi_asi_ccd: Received 1 fds
Nov 16 08:03:02 allsky indiserver[626205]: 2022-11-15T21:03:02: Driver indi_asi_ccd: Received 1 fds
Nov 16 08:03:17 allsky indiserver[626205]: 2022-11-15T21:03:17: Driver indi_asi_ccd: Received 1 fds
Nov 16 08:03:32 allsky indiserver[626205]: 2022-11-15T21:03:32: Driver indi_asi_ccd: Received 1 fds
Nov 16 08:03:47 allsky indiserver[626205]: 2022-11-15T21:03:47: Driver indi_asi_ccd: Received 1 fds
Nov 16 08:04:02 allsky indiserver[626205]: 2022-11-15T21:04:02: Driver indi_asi_ccd: Received 1 fds
Nov 16 08:04:17 allsky indiserver[626205]: 2022-11-15T21:04:17: Driver indi_asi_ccd: Received 1 fds

karl@allsky:/opt/allsky/images $ systemctl status --user gunicorn-indi-allsky
● gunicorn-indi-allsky.service - indi-allsky gunicorn daemon
     Loaded: loaded (/home/karl/.config/systemd/user/gunicorn-indi-allsky.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2022-11-14 03:07:18 AEDT; 2 days ago
TriggeredBy: ● gunicorn-indi-allsky.socket
   Main PID: 620 (gunicorn)
     Status: "Gunicorn arbiter booted"
      Tasks: 10 (limit: 779)
        CPU: 5min 31.781s
     CGroup: /user.slice/user-1000.slice/user@1000.service/app.slice/gunicorn-indi-allsky.service
             ├─   620 /opt/indi-allsky/virtualenv/indi-allsky/bin/python /opt/indi-allsky/virtualenv/indi-allsky/bin/gunicorn --config /etc/indi-allsky/gunicorn.conf.py indi_allsky.wsgi
             └─628661 /opt/indi-allsky/virtualenv/indi-allsky/bin/python /opt/indi-allsky/virtualenv/indi-allsky/bin/gunicorn --config /etc/indi-allsky/gunicorn.conf.py indi_allsky.wsgi

Nov 16 01:15:40 allsky gunicorn[626519]: [INFO] MainProcess views.dispatch_request() #1261: Wrote new config.json
Nov 16 01:15:41 allsky gunicorn[626519]: [INFO] MainProcess glogging.info() #264: Worker exiting (pid: 626519)
Nov 16 01:15:42 allsky gunicorn[628661]: [2022-11-16 01:15:42 +1100] [628661] [INFO] Booting worker with pid: 628661
Nov 16 01:15:42 allsky gunicorn.indi_allsky.wsgi.error[628661]: [628661] Booting worker with pid: 628661
Nov 16 01:16:07 allsky gunicorn[628661]: [INFO] MainProcess views.dispatch_request() #1861: Command return: /org/freedesktop/systemd1/job/73
Nov 16 01:16:07 allsky gunicorn[628661]: [INFO] MainProcess views.dispatch_request() #1861: Command return: /org/freedesktop/systemd1/job/73
Nov 16 08:14:36 allsky gunicorn[628661]: [INFO] MainProcess forms.__init__() #1739: Dates processed in 0.0213 s
Nov 16 08:14:36 allsky gunicorn[628661]: [INFO] MainProcess forms.__init__() #1739: Dates processed in 0.0213 s
Nov 16 12:40:25 allsky gunicorn[628661]: [INFO] MainProcess forms.__init__() #1739: Dates processed in 0.0066 s
Nov 16 12:40:25 allsky gunicorn[628661]: [INFO] MainProcess forms.__init__() #1739: Dates processed in 0.0066 s

```

**Comment by aaronwmorris** [comment]
Merged #416 to make the main process loop more resilient to out of space conditions.

**Comment by Vertikar** [comment]
Great thanks, I can probably test relatively soon and report back

**Comment by Vertikar** [comment]
Looks all good, and recovers fine after clearing the space.

Here's the log output of after i filled the disk

```
Nov 20 15:35:11 allsky [INFO] MainProcess indi.newBLOB() #172: new BLOB CCD1
Nov 20 15:35:11 allsky [ERROR] MainProcess indi.newBLOB() #192: OSError: Not enough space on disk: requested 2545408, available 0. Not enough space on disk: requested 2545408, available 0. [Errno 28] No space left on device
Nov 20 15:35:11 allsky [INFO] MainProcess allsky.run() #783: Exposure received in 0.8239 s (0.8076)
Nov 20 15:35:21 allsky [INFO] MainProcess allsky.shoot() #1276: Taking 0.01635809 s exposure (gain 0)
Nov 20 15:35:21 allsky [INFO] MainProcess allsky.run() #841: Total time since last exposure 10.0442 s
Nov 20 15:35:21 allsky [INFO] MainProcess allsky.run() #679: Camera last ready: 9.4s
Nov 20 15:35:21 allsky [INFO] MainProcess allsky.run() #680: Exposure state: OK
Nov 20 15:35:21 allsky [INFO] MainProcess allsky.detectNight() #1054: Sun altitude: 52:26:02.4
Nov 20 15:35:21 allsky [INFO] MainProcess allsky.detectMoonMode() #1071: Moon altitide: 4:54:03.3, phase 16.9%
Nov 20 15:35:21 allsky [INFO] MainProcess indi.getCcdTemperature() #489: Sensor temperature: 26.7
Nov 20 15:35:21 allsky [INFO] MainProcess allsky._queueManualTasks() #1760: Checking for manually submitted tasks
Nov 20 15:35:21 allsky [INFO] MainProcess indi.newText() #236: new Text DRIVER_INFO for device ZWO CCD ASI224MC
Nov 20 15:35:21 allsky [INFO] MainProcess indi.newMessage() #242: new Message 2022-11-20T04:35:21: [WARNING] Telescope focal length is missing.
Nov 20 15:35:21 allsky [INFO] MainProcess indi.newMessage() #242: new Message 2022-11-20T04:35:21: [WARNING] Telescope aperture is missing.
Nov 20 15:35:21 allsky [INFO] MainProcess indi.newBLOB() #172: new BLOB CCD1
Nov 20 15:35:21 allsky [ERROR] MainProcess indi.newBLOB() #192: OSError: Not enough space on disk: requested 2545408, available 0. Not enough space on disk: requested 2545408, available 0. [Errno 28] No space left on device
Nov 20 15:35:21 allsky [INFO] MainProcess allsky.run() #783: Exposure received in 0.6740 s (0.6576)
Nov 20 15:35:31 allsky [INFO] MainProcess allsky.shoot() #1276: Taking 0.01635809 s exposure (gain 0)
Nov 20 15:35:31 allsky [INFO] MainProcess allsky.run() #841: Total time since last exposure 10.0429 s
Nov 20 15:35:31 allsky [INFO] MainProcess indi.newText() #236: new Text DRIVER_INFO for device ZWO CCD ASI224MC
Nov 20 15:35:31 allsky [INFO] MainProcess indi.newMessage() #242: new Message 2022-11-20T04:35:31: [WARNING] Telescope focal length is missing.
Nov 20 15:35:31 allsky [INFO] MainProcess indi.newMessage() #242: new Message 2022-11-20T04:35:31: [WARNING] Telescope aperture is missing.
Nov 20 15:35:31 allsky [INFO] MainProcess indi.newBLOB() #172: new BLOB CCD1
Nov 20 15:35:31 allsky [ERROR] MainProcess indi.newBLOB() #192: OSError: Not enough space on disk: requested 2545408, available 0. Not enough space on disk: requested 2545408, available 0. [Errno 28] No space left on device
Nov 20 15:35:31 allsky [INFO] MainProcess allsky.run() #783: Exposure received in 0.6705 s (0.6541)
Nov 20 15:35:32 allsky [INFO] MainProcess allsky.run() #679: Camera last ready: 0.5s
Nov 20 15:35:32 allsky [INFO] MainProcess allsky.run() #680: Exposure state: OK
```
