### ISSUE TITLE
setup

### ISSUE THREAD

**Issue by ruirigel** [aaronwmorris/indi-allsky#80]
following your manual I am trying to setup indi allsky on a Raspbian Buster distro but I am having problems starting indi-allsky from here:
$ systemctl --user start indi-allsky
- I don't see anything that says the service is running
- i can't get into the web interface 
- when i try to manually start ./allsky.py run
```
pi@raspberrypi:~/indi-allsky $ ./allsky.py run
Traceback (most recent call last):
  File "./allsky.py", line 3, in <module>
    import indi_allsky
  File "/home/pi/indi-allsky/indi_allsky/__init__.py", line 1, in <module>
    from .allsky import IndiAllSky
  File "/home/pi/indi-allsky/indi_allsky/allsky.py", line 15, in <module>
    import ephem
ModuleNotFoundError: No module named 'ephem'

```

everything in respect with the indiserver service seems fine

**Comment by aaronwmorris** [comment]
If you want to manually run, you just need to activate the python virtualenv where the modules are installed.

`source virtualenv/indi-allsky/bin/activate`

**Comment by ruirigel** [comment]
I did everything you suggested. I don't have the folder or the log file in  /var/log/ perhaps because the service has not yet started its first time.
When I start indi-allsky via systemctl here is what appears:


```
pi@raspberrypi:~/indi-allsky $ systemctl --user start indi-allsky 
pi@raspberrypi:~/indi-allsky $ systemctl --user status indi-allsky
● indi-allsky.service - Indi AllSky Service
   Loaded: loaded (/home/pi/.config/systemd/user/indi-allsky.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sat 2022-02-12 19:14:22 WET; 6s ago
  Process: 2422 ExecStart=/home/pi/indi-allsky/virtualenv/indi-allsky/bin/python3 allsky.py --config /etc/indi-allsky/config.json --log sy
 Main PID: 2422 (code=exited, status=1/FAILURE)

fev 12 19:14:21 raspberrypi python3[2422]: Traceback (most recent call last):
fev 12 19:14:21 raspberrypi python3[2422]:   File "allsky.py", line 12, in <module>
fev 12 19:14:21 raspberrypi python3[2422]:     app = indi_allsky.flask.create_app()
fev 12 19:14:21 raspberrypi python3[2422]:   File "/home/pi/indi-allsky/indi_allsky/flask/__init__.py", line 66, in create_app
fev 12 19:14:21 raspberrypi python3[2422]:     app.config.from_file(p_flask_config, load=json.load)
fev 12 19:14:21 raspberrypi python3[2422]:   File "/home/pi/indi-allsky/virtualenv/indi-allsky/lib/python3.7/site-packages/flask/config.py
fev 12 19:14:21 raspberrypi python3[2422]:     with open(filename) as f:
fev 12 19:14:21 raspberrypi python3[2422]: FileNotFoundError: [Errno 2] Unable to load configuration file (No such file or directory): '/e
fev 12 19:14:22 raspberrypi systemd[618]: indi-allsky.service: Main process exited, code=exited, status=1/FAILURE
fev 12 19:14:22 raspberrypi systemd[618]: indi-allsky.service: Failed with result 'exit-code'.

```

**Comment by aaronwmorris** [comment]
You can run setup.sh multiple times.  It looks like the setup did not complete in the first place.

I would run it again and let me know if it return any errors.

**Comment by aaronwmorris** [comment]
I found a race condition in the setup that was preventing it from completing on a new install.  Pull down the latest code and it should be fixed.

**Comment by ruirigel** [comment]
> I found a race condition in the setup that was preventing it from completing on a new install. Pull down the latest code and it should be fixed.

everything seems to be ok now, web interface works, indi-allsky service is down but it seems that it's just because of not having ccd connected yet.

```
...
A configuration file has automatically been provisioned at /etc/indi-allsky/config.json

Services can be started at the command line or can be started from the web interface

    systemctl --user start indiserver
    systemctl --user start indi-allsky


The web interface may be accessed with the following URL
 (You may have to manually access by IP)

    https://raspberrypi/

Enjoy!
pi@raspberrypi:~/indi-allsky $ systemctl --user status indi-allsky
● indi-allsky.service - Indi AllSky Service
   Loaded: loaded (/home/pi/.config/systemd/user/indi-allsky.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sat 2022-02-12 21:47:28 WET; 4s ago
  Process: 4708 ExecStart=/home/pi/indi-allsky/virtualenv/indi-allsky/bin/python3 allsky.py --config /etc/indi-allsky/config.json --log syslog run (code=exited, status=1/FAILURE)
 Main PID: 4708 (code=exited, status=1/FAILURE)

fev 12 21:47:18 raspberrypi python3[4708]: INDI::BaseClient::connectServer: creating new connection...
fev 12 21:47:18 raspberrypi python3[4708]: INDI::BaseClient::connectServer: Already connected.
fev 12 21:47:18 raspberrypi python3[4708]: [INFO] MainProcess indi.serverConnected() #184: Server connected (localhost:7624)
fev 12 21:47:18 raspberrypi python3[4708]: [INFO] MainProcess indi.newDevice() #128: new device Telescope Simulator
fev 12 21:47:26 raspberrypi python3[4708]: [INFO] MainProcess indi.findCcds() #316: Found device Telescope Simulator
fev 12 21:47:26 raspberrypi python3[4708]: [INFO] MainProcess indi.findCcds() #321:  Detected telescope
fev 12 21:47:26 raspberrypi python3[4708]: [INFO] MainProcess indi.findCcds() #321:  Detected guider
fev 12 21:47:26 raspberrypi python3[4708]: [ERROR] MainProcess allsky._initialize() #276: No CCDs detected
fev 12 21:47:28 raspberrypi systemd[618]: indi-allsky.service: Main process exited, code=exited, status=1/FAILURE
fev 12 21:47:28 raspberrypi systemd[618]: indi-allsky.service: Failed with result 'exit-code'.

```
